# Generated by Django 4.2.9 on 2024-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("minimum_age", models.PositiveIntegerField()),
                (
                    "verified_by",
                    models.CharField(
                        blank=True, choices=[("yivi", "Yivi"), ("manual", "Manually")], max_length=100, null=True
                    ),
                ),
                ("attributes", models.JSONField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
