# Generated by Django 4.2.4 on 2023-09-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("age", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="is18yearsold",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_18_years_old",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
