# Generated by Django 4.2.4 on 2023-09-18 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("age", "0002_alter_is18yearsold_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("session_token", models.CharField(max_length=20)),
            ],
        ),
    ]
