# Generated by Django 4.2.4 on 2023-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("age", "0003_sessionmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmapping",
            name="session_token",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
