# Generated by Django 3.0.5 on 2020-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/images/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
