# Generated by Django 3.2.13 on 2022-07-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start', '-end', 'title']},
        ),
    ]
