# Generated by Django 3.2.8 on 2021-10-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    Venue = apps.get_model("venues", "Venue")
    for venue in Venue.objects.all():
        venue.slug = slugify(venue.name)
        venue.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='can_be_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='color_in_calendar',
            field=models.CharField(blank=True, help_text='Color of reservations shown in calendar.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default="default-slug", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='associations.association')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='venues.venue')),
            ],
        ),
    ]
