# Generated by Django 5.0.8 on 2025-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="requires_basic_borrel_brevet",
            field=models.BooleanField(default=True),
        ),
    ]
