# Generated by Django 3.0.5 on 2020-05-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="venue", name="image",),
    ]
