# Generated by Django 3.2.8 on 2021-10-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('venues', '0002_auto_20211009_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='reservation',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='associations.association'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='can_be_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='color_in_calendar',
            field=models.CharField(blank=True, help_text='Color of reservations shown in calendar.', max_length=50, null=True),
        ),
    ]
