# Generated by Django 3.0.5 on 2020-06-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marietje", "__first__"),
        ("venues", "0002_remove_venue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="spotify_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marietje.SpotifySettings",
            ),
        ),
    ]
