# Generated by Django 3.2.16 on 2022-12-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0003_auto_20221210_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
