# Generated by Django 4.1.7 on 2023-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_auto_20221218_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="automatically_accept_first_reservation",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, a reservation placed on this venue will be automatically accepted if it does not overlap with another reservation.",
            ),
        ),
    ]
