# Generated by Django 4.2.4 on 2023-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_venue_automatically_accept_first_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="needs_music_keys",
            field=models.BooleanField(
                default=False, help_text="Whether the music keys are needed during this reservation."
            ),
        ),
    ]
