# Generated by Django 3.1.3 on 2021-01-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marietje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyqueueitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='marietje.player'),
        ),
    ]
