# Generated by Django 3.0.5 on 2020-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marietje", "0002_auto_20200531_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifysettings",
            name="playback_device_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="spotifysettings",
            name="display_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="spotifysettings",
            name="playback_device_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
