# Generated by Django 3.0.5 on 2020-06-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marietje", "0003_auto_20200531_2340"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotifysettings",
            options={
                "verbose_name": "Spotify settings",
                "verbose_name_plural": "Spotify settings",
            },
        ),
    ]
