# Generated by Django 3.0.5 on 2020-07-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupsettings'),
        ('marietje', '0003_auto_20200628_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyqueueitem',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User'),
        ),
    ]
