# Generated by Django 3.0.5 on 2020-06-13 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marietje", "0004_auto_20200601_0940"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyArtist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=2048, unique=True)),
                ("artist_id", models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name="SpotifyTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=256, unique=True)),
                ("track_name", models.CharField(max_length=1024)),
                ("track_artists", models.ManyToManyField(to="marietje.SpotifyArtist")),
            ],
        ),
        migrations.CreateModel(
            name="SpotifyQueueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_created=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spotify_settings_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marietje.SpotifySettings",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marietje.SpotifyTrack",
                    ),
                ),
            ],
            options={"ordering": ["added"],},
        ),
    ]
