# Generated by Django 3.2.13 on 2022-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ready', models.BooleanField(default=False)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Ordered'), (1, 'Scanned')], default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
