# Generated by Django 3.0.5 on 2020-07-08 11:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVenue',
            fields=[
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='venues.Venue')),
            ],
            options={
                'ordering': ['venue__name'],
                'permissions': [('can_order_in_venue', 'Can order products during shifts in this venue'), ('can_manage_shift_in_venue', 'Can manage shifts in this venue')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=orders.models.get_default_start_time_shift)),
                ('end_date', models.DateTimeField(default=orders.models.get_default_end_time_shift)),
                ('can_order', models.BooleanField(default=False, help_text='If checked, people can order within the given time frame. If not checked, ordering will not be possible, even in the given time frame.', verbose_name='Orders allowed')),
                ('max_orders_per_user', models.PositiveSmallIntegerField(blank=True, default=2, help_text='The maximum amount of products a single user can order in this shift. Empty means no limit.', null=True, verbose_name='Max. number of orders per user')),
                ('max_orders_total', models.PositiveSmallIntegerField(blank=True, default=50, help_text='The maximum amount of products that can be ordered during this shift in total. Empty means no limit.', null=True, verbose_name='Max. total number of orders')),
                ('assignees', models.ManyToManyField(to='users.User')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.OrderVenue', validators=[orders.models.active_venue_validator])),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Font-awesome icon name that is used for quick display of the product type.', max_length=20, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_allowed_per_shift', models.PositiveSmallIntegerField(blank=True, default=2, help_text='The maximum amount a single user can order this product in a single shift. Note that shifts are bound to the venue. Empty means no limit.', null=True, verbose_name='Max. allowed orders per shift')),
                ('available_at', models.ManyToManyField(to='orders.OrderVenue')),
            ],
            options={
                'ordering': ['-available', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ready', models.BooleanField(default=False)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Product', validators=[orders.models.available_product_filter])),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Shift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
