# Generated by Django 3.0.5 on 2020-05-08 16:44

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="end_date",
            field=models.DateTimeField(
                default=orders.models.get_default_end_time_shift
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_date",
            field=models.DateTimeField(
                default=orders.models.get_default_start_time_shift
            ),
        ),
    ]
