# Generated by Django 3.0.5 on 2020-04-27 20:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_allowed_per_shift',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='The maximum amount a single user can order this product in a single shift. Note that shifts are bound to the venue. Empty means no limit.', null=True, verbose_name='Max. allowed orders per shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='max_orders_per_user',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='The maximum amount of products a single user can order in this shift. Empty means no limit.', null=True, verbose_name='Max. number of orders per user'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='max_orders_total',
            field=models.PositiveSmallIntegerField(blank=True, default=50, help_text='The maximum amount of products that can be ordered during this shift in total. Empty means no limit.', null=True, verbose_name='Max. total number of orders'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='orders_allowed',
            field=models.BooleanField(default=False, help_text='If checked, people can order within the given time frame. If not checked, ordering will not be possible, even in the given time frame.', verbose_name='Orders allowed'),
        ),
    ]
