# Generated by Django 3.0.8 on 2020-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Ordered'), (1, 'Scanned')], default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Either an EAN-8 or EAN-13 barcode.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ignore_shift_restrictions',
            field=models.BooleanField(default=False, help_text='Whether or not this product should ignore the maximum orders per shift restriction.'),
        ),
        migrations.AddField(
            model_name='product',
            name='orderable',
            field=models.BooleanField(default=True, help_text='Whether or not this product should appear on the order page.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, help_text='Font-awesome icon name that is used for quick display of the product type.', max_length=20, null=True),
        ),
    ]
