# Generated by Django 3.0.8 on 2020-11-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('orders', '0002_auto_20200812_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='associations.Association'),
        ),
    ]
