# Generated by Django 3.2.6 on 2021-08-04 12:20

from django.db import migrations, models


def set_fields_to_non_null(apps, schema_editor):
    Product = apps.get_model("orders", "Product")
    for product in Product.objects.filter(icon=None):
        product.icon = ""
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user_association'),
    ]

    operations = [
        migrations.RunPython(set_fields_to_non_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Font-awesome icon name that is used for quick display of the product type.', max_length=20),
        ),
    ]
