# Generated by Django 3.2.14 on 2022-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordervenue',
            options={'ordering': ['venue__name'], 'permissions': [('can_manage_shift_in_venue', 'Can manage shifts in this venue'), ('gets_prioritized_orders_in_venue', 'Gets prioritized orders in this venue')]},
        ),
        migrations.AddField(
            model_name='order',
            name='prioritize',
            field=models.BooleanField(default=False),
        ),
    ]
