# Generated by Django 3.1.6 on 2021-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='finalized',
            field=models.BooleanField(default=False, help_text='If checked, shift is finalized and no alterations on the shift can be made anymore.', verbose_name='Shift Finalized'),
        ),
    ]
