# Generated by Django 3.0.5 on 2020-06-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_auto_20200512_0831"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={
                "ordering": ["start_date", "end_date"],
                "permissions": [
                    ("can_order_during_shift", "Can order products during this shift"),
                    (
                        "can_process_during_shift",
                        "Can process orders during this shift",
                    ),
                    (
                        "can_process_after_shift",
                        "Can process orders after shift has ended",
                    ),
                ],
            },
        ),
    ]
