# Generated by Django 3.2.8 on 2021-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210804_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='finalized',
            field=models.BooleanField(default=False, help_text='If checked, shift is finalized and no alterations on the shift can be made anymore.', verbose_name='Shift Finalized'),
        ),
    ]
