# Generated by Django 3.2.15 on 2022-10-20 11:39

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderblacklisteduser_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='max_orders_total',
            field=models.PositiveSmallIntegerField(blank=True, default=orders.models.get_default_max_orders_total, help_text='The maximum amount of products that can be ordered during this shift in total. Empty means no limit.', null=True, verbose_name='Max. total number of orders'),
        ),
    ]
