# Generated by Django 4.2.7 on 2023-12-14 16:19

from django.db import migrations, models

PRIORITY_PRIORITIZED = 2
PRIORITY_DEPRIORITIZED = 0


def set_new_priority_field(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all():
        if order.prioritize:
            order.priority = PRIORITY_PRIORITIZED
            order.save()
        elif order.deprioritize:
            order.priority = PRIORITY_DEPRIORITIZED
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_deprioritize"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="priority",
            field=models.PositiveIntegerField(
                choices=[(0, "Deprioritized"), (1, "Normal"), (2, "Prioritized")], default=1
            ),
        ),
        migrations.RunPython(set_new_priority_field),
        migrations.RemoveField(
            model_name="order",
            name="deprioritize",
        ),
        migrations.RemoveField(
            model_name="order",
            name="prioritize",
        ),
    ]
