# Generated by Django 3.2.12 on 2022-03-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211211_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start', 'end']},
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='start_date',
            new_name='start',
        ),
    ]
