# Generated by Django 3.0.5 on 2020-07-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200706_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_date', 'end_date']},
        ),
    ]
