# Generated by Django 4.2.4 on 2023-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_deprioritize"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="picked_up",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="picked_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="picked_up",
            field=models.BooleanField(default=False),
        ),
    ]
