# Generated by Django 4.2.9 on 2024-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="picked_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="picked_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
