# Generated by Django 3.2.12 on 2022-03-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220313_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start', '-end']},
        ),
    ]
