# Generated by Django 3.0.5 on 2020-07-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupsettings'),
        ('orders', '0008_auto_20200706_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='assignees',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
