# Generated by Django 3.0.8 on 2020-07-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('playback_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('playback_device_name', models.CharField(blank=True, help_text='When configuring this Spotify account for the first time, make sure to have the Spotify accounnt active on at least one playback device to complete configuration.', max_length=256, null=True)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('venue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.Venue')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'permissions': [('can_control', 'Can control music players'), ('can_request', 'Can request songs')],
            },
        ),
        migrations.CreateModel(
            name='SpotifyArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255, unique=True)),
                ('artist_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255, unique=True)),
                ('track_name', models.CharField(max_length=255)),
                ('track_artists', models.ManyToManyField(to='thaliedje.SpotifyArtist')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thaliedje.Player')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thaliedje.SpotifyTrack')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
