# Generated by Django 3.2.13 on 2022-06-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('playback_device_id', models.CharField(blank=True, default='', max_length=255)),
                ('playback_device_name', models.CharField(blank=True, default='', help_text='When configuring this Spotify account for the first time, make sure to have the Spotify accounnt active on at least one playback device to complete configuration.', max_length=255)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'permissions': [('can_control', 'Can control music players'), ('can_request', 'Can request songs')],
            },
        ),
        migrations.CreateModel(
            name='SpotifyArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255, unique=True)),
                ('artist_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255, unique=True)),
                ('track_name', models.CharField(max_length=255)),
                ('track_artists', models.ManyToManyField(to='thaliedje.SpotifyArtist')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='thaliedje.player')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
