# Generated by Django 3.2.13 on 2022-06-24 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        ('thaliedje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thaliedjeblacklisteduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spotifytrack',
            name='track_artists',
            field=models.ManyToManyField(to='thaliedje.SpotifyArtist'),
        ),
        migrations.AddField(
            model_name='spotifyqueueitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='thaliedje.player'),
        ),
        migrations.AddField(
            model_name='spotifyqueueitem',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spotifyqueueitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='thaliedje.spotifytrack'),
        ),
        migrations.AddField(
            model_name='player',
            name='venue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue'),
        ),
    ]
