# Generated by Django 4.2.9 on 2024-04-08 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("thaliedje", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thaliedjecontrolevent",
            name="event",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="venues.reservation"),
        ),
        migrations.AddField(
            model_name="thaliedjecontrolevent",
            name="selected_users",
            field=models.ManyToManyField(
                blank=True, related_name="thaliedje_control_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="thaliedjeblacklisteduser",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="spotifytrack",
            name="track_artists",
            field=models.ManyToManyField(to="thaliedje.spotifyartist"),
        ),
        migrations.AddField(
            model_name="spotifyqueueitem",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="thaliedje.player"
            ),
        ),
        migrations.AddField(
            model_name="spotifyqueueitem",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spotifyqueueitem",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="thaliedje.spotifytrack",
            ),
        ),
        migrations.AddField(
            model_name="playerlogentry",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="thaliedje.player"
            ),
        ),
        migrations.AddField(
            model_name="playerlogentry",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="venue",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="venues.venue"
            ),
        ),
    ]
