# Generated by Django 3.2.6 on 2021-08-04 12:20

from django.db import migrations, models
import django.db.models.deletion


def set_fields_to_non_null(apps, schema_editor):
    Player = apps.get_model("thaliedje", "Player")
    for player in Player.objects.all():
        if player.display_name is None:
            player.display_name = ""
        if player.playback_device_id is None:
            player.playback_device_id = ""
        if player.playback_device_name is None:
            player.playback_device_name = ""


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
        ('thaliedje', '0002_auto_20210117_1856'),
    ]

    operations = [
        migrations.RunPython(set_fields_to_non_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='playback_device_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='playback_device_name',
            field=models.CharField(blank=True, default='', help_text='When configuring this Spotify account for the first time, make sure to have the Spotify accounnt active on at least one playback device to complete configuration.', max_length=256),
        ),
        migrations.AlterField(
            model_name='spotifyartist',
            name='artist_id',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifyartist',
            name='artist_name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifyqueueitem',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='spotifyqueueitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thaliedje.spotifytrack'),
        ),
        migrations.AlterField(
            model_name='spotifytrack',
            name='track_name',
            field=models.CharField(max_length=256),
        ),
    ]
