# Generated by Django 6.0.8 on 2026-10-05 11:54

import django.db.models.deletion
from django.db import migrations, models


def populate_player_names(apps, schema_editor):
    PlayerLogEntry = apps.get_model("thaliedje", "PlayerLogEntry")
    database = schema_editor.connection.alias
    logs = PlayerLogEntry.objects.using(database).select_related("player").iterator()
    batch = []
    for log in logs:
        log.player_name = log.player.display_name if log.player_id else ""
        batch.append(log)
        if len(batch) == 500:
            PlayerLogEntry.objects.using(database).bulk_update(batch, ["player_name"])
            batch.clear()
    if batch:
        PlayerLogEntry.objects.using(database).bulk_update(batch, ["player_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlogentry',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(populate_player_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='playerlogentry',
            name='player',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='logs',
                to='thaliedje.player',
            ),
        ),
    ]
