# Generated by Django 3.2.13 on 2022-07-05 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
