# Generated by Django 6.0.6 on 2026-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thaliedje", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyqueueitem",
            name="observed_at_position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Queue position this request was last seen at, or NULL if we have not matched it to a live Spotify queue entry. Set by the queue observer task.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="spotifyqueueitem",
            name="played_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Moment this request was observed to leave the Spotify queue (either played through or skipped). NULL means still queued, or status unknown if the observer hasn't run lately.",
                null=True,
            ),
        ),
    ]
