# Generated by Django 3.2.13 on 2022-07-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0003_auto_20220705_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_volume',
        ),
    ]
