# Generated by Django 3.2.13 on 2022-07-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0004_remove_player_current_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(default='noord', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
