# Generated by Django 3.2.14 on 2022-07-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0005_player_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'permissions': [('can_control', 'Can control music players'), ('can_request_playlists_and_albums', 'Can request playlists and albums')], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
