# Generated by Django 3.2.14 on 2022-07-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0006_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thaliedjeblacklisteduser',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
