# Generated by Django 3.2.15 on 2022-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaliedje', '0007_thaliedjeblacklisteduser_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyartist',
            name='artist_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifyartist',
            name='artist_name',
            field=models.CharField(max_length=255),
        ),
    ]
