# Generated by Django 4.1.4 on 2023-01-17 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("thaliedje", "0009_playerlogentry_thaliedjecontrolevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarietjePlayer",
            fields=[
                (
                    "player_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="thaliedje.player",
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=255)),
            ],
            bases=("thaliedje.player",),
        ),
        migrations.RemoveField(
            model_name="player",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="player",
            name="client_secret",
        ),
        migrations.RemoveField(
            model_name="player",
            name="playback_device_id",
        ),
        migrations.RemoveField(
            model_name="player",
            name="playback_device_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="redirect_uri",
        ),
        migrations.AlterField(
            model_name="spotifyqueueitem",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="thaliedje.player"
            ),
        ),
        migrations.AlterField(
            model_name="spotifyqueueitem",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="spotifyqueueitem",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="thaliedje.spotifytrack",
            ),
        ),
        migrations.CreateModel(
            name="SpotifyPlayer",
            fields=[
                (
                    "player_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="thaliedje.player",
                    ),
                ),
                ("playback_device_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "playback_device_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="When configuring this Spotify account for the first time, make sure to have the Spotify account active on at least one playback device to complete configuration.",
                        max_length=255,
                    ),
                ),
                ("client_id", models.CharField(max_length=255, unique=True)),
                ("client_secret", models.CharField(max_length=255)),
                ("redirect_uri", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Spotify player",
                "verbose_name_plural": "Spotify players",
            },
            bases=("thaliedje.player",),
        ),
    ]
