# Generated by Django 4.1.4 on 2023-01-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thaliedje", "0010_marietjeplayer_remove_player_client_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotifyplayer",
            options={
                "permissions": [
                    ("can_control", "Can control music players"),
                    ("can_request_playlists_and_albums", "Can request playlists and albums"),
                ],
                "verbose_name": "Spotify player",
                "verbose_name_plural": "Spotify players",
            },
        ),
    ]
