# Generated by Django 4.1.4 on 2023-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thaliedje", "0012_marietjeplayer_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thaliedjecontrolevent",
            name="check_throttling",
            field=models.BooleanField(default=True),
        ),
    ]
