# Generated by Django 5.0.8 on 2025-03-03 19:44

from django.db import migrations


def copy_basic_borrel_brevet(apps, schema_editor):
    QualificationsBasicBorrelBrevet = apps.get_model("qualifications", "BasicBorrelBrevet")
    BorrelBasicBorrelBrevet = apps.get_model("borrel", "BasicBorrelBrevet")
    for brevet in BorrelBasicBorrelBrevet.objects.all():
        QualificationsBasicBorrelBrevet.objects.create(user=brevet.user, registered_on=brevet.registered_on)


class Migration(migrations.Migration):

    dependencies = [
        ("borrel", "0002_initial"),
        ("qualifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_basic_borrel_brevet),
    ]
