# Generated by Django 5.0.8 on 2025-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualifications", "0002_auto_20250303_2048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicborrelbrevet",
            name="registered_on",
            field=models.DateField(auto_now_add=True),
        ),
    ]
