# Generated by Django 3.2.15 on 2022-09-21 19:12

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(max_length=500)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('icon', models.CharField(default='bullhorn', help_text='Font Awesome abbreviation for icon to use.', max_length=150, verbose_name='Font Awesome icon')),
                ('closable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-since',),
            },
        ),
    ]
