# Generated by Django 3.2.10 on 2021-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0011_auto_20210806_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idpattribute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idpuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idpuserdefaultvalue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
