# Generated by Django 4.1.9 on 2023-06-29 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("venues", "0005_venue_automatically_accept_first_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fridge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If the fridge is active, it will be shown on the website and can be opened by users within the set opening hours. People with 'open always' permissions can always open the fridge, regardless of whether it is active.",
                    ),
                ),
                (
                    "unlock_for_how_long",
                    models.DurationField(
                        default=datetime.timedelta(seconds=60),
                        help_text="How long to unlock the fridge for by default (HH:MM:SS).",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="venues.venue"
                    ),
                ),
            ],
            options={
                "verbose_name": "fridge",
                "verbose_name_plural": "fridges",
                "ordering": ["name"],
                "permissions": [("open_always", "Can always open fridges")],
            },
        ),
        migrations.CreateModel(
            name="BlacklistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fridge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fridges.fridge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "blacklist entry",
                "verbose_name_plural": "blacklist entries",
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("fridge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fridges.fridge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "access log",
                "verbose_name_plural": "access logs",
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="GeneralOpeningHours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("fridge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fridges.fridge")),
                (
                    "restrict_to_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only allow members of these groups to open the fridge during these opening hours.",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "general opening hours",
                "verbose_name_plural": "general opening hours",
                "ordering": ["weekday", "start_time"],
                "unique_together": {("weekday", "start_time", "end_time", "fridge")},
            },
        ),
    ]
