# Generated by Django 4.2.4 on 2023-09-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fridge",
            name="minimum_age",
            field=models.PositiveIntegerField(
                blank=True,
                default=18,
                help_text="Minimum age required for a user to open the fridge. People with 'open always' permissions can always open the fridge, regardless of what their age is.",
                null=True,
            ),
        ),
    ]
