# Generated by Django 4.2.9 on 2024-04-08 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fridges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fridge",
            name="venue",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="venues.venue"
            ),
        ),
        migrations.AddField(
            model_name="blacklistentry",
            name="fridge",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fridges.fridge"),
        ),
        migrations.AddField(
            model_name="blacklistentry",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="fridge",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fridges.fridge"),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="generalopeninghours",
            unique_together={("weekday", "start_time", "end_time", "fridge")},
        ),
    ]
