# Generated by Django 6.0.5 on 2026-06-01 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("restock_default", models.IntegerField(default=0)),
                ("stock_amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Restock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restock_time", models.DateTimeField(auto_now_add=True)),
                (
                    "restocked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tampon.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "Restock record",
                "verbose_name_plural": "Restock records",
                "ordering": ["-restock_time"],
            },
        ),
        migrations.CreateModel(
            name="RestockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "restock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tampon.restock"
                    ),
                ),
                (
                    "stock_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tampon.stockdata",
                    ),
                ),
            ],
            options={
                "unique_together": {("restock", "stock_data")},
            },
        ),
        migrations.AddField(
            model_name="restock",
            name="stock_items",
            field=models.ManyToManyField(
                related_name="restocks",
                through="tampon.RestockItem",
                to="tampon.stockdata",
            ),
        ),
        migrations.CreateModel(
            name="TamponNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tampon.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tampon notification",
                "verbose_name_plural": "Tampon notifications",
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_tamponnotification", "Can manage Tampon notifications")
                ],
            },
        ),
    ]
