# Generated by Django 6.0.5 on 2026-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tampon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="building",
            field=models.CharField(
                choices=[("hg", "Huygens")], default="hg", max_length=10
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("building", "floor_number", "room_number")},
        ),
    ]
