# Generated by Django 6.0.5 on 2026-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tampon", "0002_alter_room_building_alter_room_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="room",
            name="building",
        ),
        migrations.RemoveField(
            model_name="room",
            name="floor_number",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_code",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_number",
        ),
    ]
