# Generated by Django 6.0.5 on 2026-05-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tampon", "0003_alter_room_unique_together_room_name_room_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tamponnotification",
            old_name="notification_text",
            new_name="comment",
        ),
    ]
