"""
Django settings for tosti project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from tosti.settings import *  # noqa

SECRET_KEY = "7c^z*je^r!@aw!0*vuc1t4cp1rfi+4+xu@x5pva@xc@rf%3#lt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "0.0.0.0"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler",},  # noqa
    },  # noqa
    "loggers": {
        "": {"handlers": ["console"], "level": "INFO", "propagate": True,},  # noqa
    },  # noqa
}

SPOTIFY_CACHE_PATH = os.path.join(BASE_DIR, "cache")  # noqa
