# Generated by Django 4.1.7 on 2023-04-08 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associations", "0001_initial"),
        ("orders", "0007_order_deprioritize"),
        ("borrel", "0006_alter_borrelreservation_join_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CachedRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SilvasoftShiftSynchronization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("succeeded", models.BooleanField()),
                ("shift", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.shift")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SilvasoftShiftInvoice",
            fields=[
                (
                    "silvasoft_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("shift", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.shift")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SilvasoftOrderVenue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_customer_number", models.IntegerField(unique=True)),
                (
                    "order_venue",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.ordervenue"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SilvasoftOrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_product_number", models.CharField(max_length=100, unique=True)),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.product")),
            ],
        ),
        migrations.CreateModel(
            name="SilvasoftBorrelReservationSynchronization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("succeeded", models.BooleanField()),
                (
                    "borrel_reservation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="borrel.borrelreservation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SilvasoftBorrelReservationInvoice",
            fields=[
                (
                    "silvasoft_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "borrel_reservation",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="borrel.borrelreservation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SilvasoftBorrelProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_product_number", models.CharField(max_length=100, unique=True)),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="borrel.product")),
            ],
        ),
        migrations.CreateModel(
            name="SilvasoftAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_customer_number", models.IntegerField(unique=True)),
                (
                    "association",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="associations.association"),
                ),
            ],
        ),
    ]
