# Generated by Django 4.1.7 on 2023-03-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_order_deprioritize"),
        ("borrel", "0006_alter_borrelreservation_join_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SilvasoftShiftSynchronization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("shift", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.shift")),
            ],
        ),
        migrations.CreateModel(
            name="SilvasoftBorrelReservationSynchronization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "borrel_reservation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="borrel.borrelreservation"),
                ),
            ],
        ),
    ]
