# Generated by Django 4.2 on 2023-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silvasoft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="silvasoftborrelproduct",
            name="cost_center",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="silvasoftorderproduct",
            name="cost_center",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
