# Generated by Django 4.2.9 on 2024-04-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_initial"),
        ("silvasoft", "0001_initial"),
        ("borrel", "0002_initial"),
        ("associations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="silvasoftshiftsynchronization",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="silvasoft_synchronization",
                to="orders.shift",
            ),
        ),
        migrations.AddField(
            model_name="silvasoftshiftinvoice",
            name="shift",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="silvasoft_invoice", to="orders.shift"
            ),
        ),
        migrations.AddField(
            model_name="silvasoftordervenue",
            name="order_venue",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.ordervenue"),
        ),
        migrations.AddField(
            model_name="silvasoftorderproduct",
            name="product",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.product"),
        ),
        migrations.AddField(
            model_name="silvasoftborrelreservationsynchronization",
            name="borrel_reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="silvasoft_synchronization",
                to="borrel.borrelreservation",
            ),
        ),
        migrations.AddField(
            model_name="silvasoftborrelreservationinvoice",
            name="borrel_reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="silvasoft_invoice",
                to="borrel.borrelreservation",
            ),
        ),
        migrations.AddField(
            model_name="silvasoftborrelproduct",
            name="product",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="borrel.product"),
        ),
        migrations.AddField(
            model_name="silvasoftassociation",
            name="association",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="associations.association"),
        ),
    ]
