# Generated by Django 4.1.7 on 2023-04-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0001_initial"),
        ("silvasoft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SilvasoftAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_customer_number", models.IntegerField()),
                (
                    "association",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="associations.association"),
                ),
            ],
        ),
    ]
