# Generated by Django 4.2 on 2023-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silvasoft", "0002_silvasoftborrelproduct_cost_center_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silvasoftborrelproduct",
            name="cost_center",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="silvasoftorderproduct",
            name="cost_center",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
