# Generated by Django 4.1.7 on 2023-04-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_deprioritize"),
        ("silvasoft", "0002_cachedrelation_silvasoftassociation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="silvasoftassociation",
            name="silvasoft_customer_number",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="SilvasoftOrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_product_number", models.CharField(max_length=100)),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.product")),
            ],
        ),
    ]
