# Generated by Django 4.1.7 on 2023-04-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("borrel", "0006_alter_borrelreservation_join_code"),
        ("silvasoft", "0003_cachedproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silvasoftorderproduct",
            name="silvasoft_product_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="SilvasoftBorrelProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("silvasoft_product_number", models.CharField(max_length=100, unique=True)),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="borrel.product")),
            ],
        ),
    ]
