# Generated by Django 3.0.5 on 2020-07-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group')),
                ('is_auto_join_group', models.BooleanField(default=False, help_text='If enabled, new users will automatically join this group.')),
                ('gets_staff_permissions', models.BooleanField(default=False, help_text='If enabled, all members added to this group will automatically get staff status after their next login. This staff status will not be automatically revoked, though, if the user leaves the group.')),
            ],
            options={
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
    ]
