# Generated by Django 3.0.5 on 2020-06-29 15:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0014_auto_20200629_1658"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.group",),
            managers=[("objects", django.contrib.auth.models.GroupManager()),],
        ),
        migrations.DeleteModel(name="User",),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.user",),
        ),
    ]
