# Generated by Django 3.0.5 on 2020-06-28 10:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0002_generic_permissions_index"),
        ("auth", "0011_update_proxy_permissions"),
        ("users", "0002_usergroup"),
    ]

    operations = [
        migrations.RemoveField(model_name="usergroup", name="group_ptr",),
        migrations.DeleteModel(name="User",),
        migrations.DeleteModel(name="UserGroup",),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.user",),
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.group",),
            managers=[("objects", django.contrib.auth.models.GroupManager()),],
        ),
    ]
