# Generated by Django 3.0.5 on 2020-07-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200706_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Group')),
                ('is_auto_join_group', models.BooleanField(default=False, help_text='If enabled, new users will automatically join this group.')),
                ('gets_staff_permissions', models.BooleanField(default=False, help_text='If enabled, all members in this group will get staff permissions.')),
            ],
        ),
    ]
