# Generated by Django 3.0.5 on 2020-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200427_1451"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="active",),
        migrations.RemoveField(model_name="user", name="admin",),
        migrations.RemoveField(model_name="user", name="staff",),
        migrations.RemoveField(model_name="user", name="timestamp",),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="email address"
            ),
            preserve_default=False,
        ),
    ]
