# Generated by Django 3.0.5 on 2020-06-28 11:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_auto_20200628_1301"),
        ("users", "0003_auto_20200628_1253"),
    ]

    operations = [
        migrations.DeleteModel(name="UserGroup",),
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.group",),
            managers=[("objects", django.contrib.auth.models.GroupManager()),],
        ),
    ]
