# Generated by Django 4.1.7 on 2023-03-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsettings",
            name="display_on_website",
            field=models.BooleanField(
                default=False, help_text="If enabled, the members of this group will be displayed on a webpage."
            ),
        ),
        migrations.AlterField(
            model_name="groupsettings",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="settings",
                serialize=False,
                to="auth.group",
            ),
        ),
    ]
