# Generated by Django 3.0.5 on 2020-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200707_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsettings',
            options={'ordering': ['group__name']},
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='gets_staff_permissions',
            field=models.BooleanField(default=False, help_text='If enabled, all members added to this group will get staff status after their next login. Staff status will not be revoked, even though permissions are.'),
        ),
    ]
