# Generated by Django 3.0.5 on 2020-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200707_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsettings',
            name='gets_staff_permissions',
            field=models.BooleanField(default=False, help_text='If enabled, all members added to this group will automatically get staff status after their next login. This staff status will not be automatically revoked, though, if the user leaves the group.'),
        ),
    ]
