# Generated by Django 3.2.8 on 2021-10-19 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0002_auto_20211012_2042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrelInventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BorrelInventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('unit_description', models.CharField(max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='borrel.borrelinventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='BorrelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, default=None, null=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations', to='associations.association')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations', to=settings.AUTH_USER_MODEL)),
                ('venue_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations', to='venues.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='BasicBorrelBrevet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_borrel_brevet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_unit_description', models.CharField(max_length=10)),
                ('product_price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_reserved', models.PositiveIntegerField()),
                ('amount_used', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_amounts', to='borrel.borrelinventoryproduct')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='borrel.borrelreservation')),
            ],
            options={
                'unique_together': {('reservation', 'product')},
            },
        ),
    ]
