# Generated by Django 3.2.8 on 2021-10-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_unit_description', models.CharField(max_length=10)),
                ('product_price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_reserved', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_used', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_amounts', to='borrel.borrelinventoryproduct')),
            ],
        ),
        migrations.AlterField(
            model_name='borrelreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrelreservation',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='borrelreservation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReservationItems',
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='borrel.borrelreservation'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationitem',
            unique_together={('reservation', 'product')},
        ),
    ]
