# Generated by Django 3.2.8 on 2021-10-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
