# Generated by Django 5.0.8 on 2025-03-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("borrel", "0002_initial"), ("qualifications", "0003_alter_basicborrelbrevet_registered_on")]

    operations = [
        migrations.DeleteModel(
            name="BasicBorrelBrevet",
        ),
    ]
