# Generated by Django 3.2.14 on 2022-07-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrel', '0003_alter_reservationitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrelreservation',
            options={'ordering': ['-start', '-end', 'title']},
        ),
    ]
