# Generated by Django 3.2.14 on 2022-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrel', '0004_alter_borrelreservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_be_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_submitted',
            field=models.BooleanField(default=True),
        ),
    ]
