# Generated by Django 3.2.10 on 2022-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrel', '0004_auto_20220225_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrelreservation',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
