# Generated by Django 3.2.10 on 2022-03-04 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrel', '0005_alter_borrelreservation_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrelreservation',
            name='user',
        ),
        migrations.AddField(
            model_name='borrelreservation',
            name='join_code',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='borrelreservation',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrelreservation',
            name='user_submitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrelreservation',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrelreservation',
            name='users_access',
            field=models.ManyToManyField(related_name='borrel_reservations_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
