# Generated by Django 3.2.16 on 2022-12-10 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrel', '0005_auto_20220719_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrelreservation',
            name='join_code',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
