# Generated by Django 3.2.10 on 2022-03-04 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrel', '0006_auto_20220304_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrelreservation',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrelreservation',
            name='user_submitted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrelreservation',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrel_reservations_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
