# Generated by Django 3.2.13 on 2022-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TantalusOrderVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TantalusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TantalusShiftSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
