# Generated by Django 3.2.5 on 2021-07-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_shift_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='TantalusShiftSynchronization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.shift')),
            ],
        ),
        migrations.CreateModel(
            name='TantalusProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='TantalusOrderVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.PositiveIntegerField()),
                ('order_venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.ordervenue')),
            ],
        ),
    ]
