# Generated by Django 3.1.6 on 2021-02-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_shift_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='TantalusProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
    ]
