# Generated by Django 3.2.13 on 2022-06-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('tantalus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tantalusshiftsynchronization',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.shift'),
        ),
        migrations.AddField(
            model_name='tantalusproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AddField(
            model_name='tantalusordervenue',
            name='order_venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.ordervenue'),
        ),
    ]
