# Generated by Django 3.2.15 on 2022-10-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_shift_max_orders_total'),
        ('borrel', '0005_auto_20220719_1328'),
        ('associations', '0001_initial'),
        ('tantalus', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TantalusProduct',
            new_name='TantalusBorrelProduct',
        ),
        migrations.AlterField(
            model_name='tantalusborrelproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrel.product'),
        ),
        migrations.CreateModel(
            name='TantalusOrdersProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='TantalusAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
            ],
        ),
    ]
