# Generated by Django 3.2.16 on 2022-11-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('borrel', '0005_auto_20220719_1328'),
        ('orders', '0006_alter_shift_max_orders_total'),
        ('tantalus', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TantalusProduct',
            new_name='TantalusOrdersProduct',
        ),
        migrations.CreateModel(
            name='TantalusBorrelReservationSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrel_reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrel.borrelreservation')),
            ],
        ),
        migrations.CreateModel(
            name='TantalusBorrelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrel.product')),
            ],
        ),
        migrations.CreateModel(
            name='TantalusAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tantalus_id', models.PositiveIntegerField()),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
            ],
        ),
    ]
