# Generated by Django 3.2.15 on 2022-10-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_shift_max_orders_total'),
        ('tantalus', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TantalusProduct',
            new_name='TantalusOrdersProduct',
        ),
    ]
