# Generated by Django 4.1.7 on 2023-04-09 07:04

from django.db import migrations


def move_tantalus_shift_synchronization_to_silvasoft(apps, schema_editor):
    TantalusShiftSynchronization = apps.get_model("tantalus", "TantalusShiftSynchronization")
    SilvasoftShiftSynchronization = apps.get_model("silvasoft", "SilvasoftShiftSynchronization")
    for tantalus_shift_synchronization in TantalusShiftSynchronization.objects.all():
        SilvasoftShiftSynchronization.objects.create(
            shift=tantalus_shift_synchronization.shift,
            succeeded=True,
        )


def move_tantalus_borrel_reservation_synchronization_to_silvasoft(apps, schema_editor):
    TantalusBorrelReservationSynchronization = apps.get_model("tantalus", "TantalusBorrelReservationSynchronization")
    SilvasoftBorrelReservationSynchronization = apps.get_model("silvasoft", "SilvasoftBorrelReservationSynchronization")
    for tantalus_borrel_reservation_synchronization in TantalusBorrelReservationSynchronization.objects.all():
        SilvasoftBorrelReservationSynchronization.objects.create(
            borrel_reservation=tantalus_borrel_reservation_synchronization.borrel_reservation,
            succeeded=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tantalus", "0003_auto_20221103_0957"),
        ("silvasoft", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tantalusborrelproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="tantalusordersproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="tantalusordervenue",
            name="order_venue",
        ),
        migrations.DeleteModel(
            name="TantalusAssociation",
        ),
        migrations.DeleteModel(
            name="TantalusBorrelProduct",
        ),
        migrations.DeleteModel(
            name="TantalusOrdersProduct",
        ),
        migrations.DeleteModel(
            name="TantalusOrderVenue",
        ),
        migrations.RunPython(
            move_tantalus_shift_synchronization_to_silvasoft, migrations.RunPython.noop
        ),
        migrations.RunPython(
            move_tantalus_borrel_reservation_synchronization_to_silvasoft, migrations.RunPython.noop
        ),
    ]
