---

name: "Linting"
on:
  - push

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Install OS dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing libxmlsec1-dev pkg-config

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: "Run Black"
        run: uv run black --check website

      - name: "Run flake8"
        run: >-
          uv run
          flake8
          --exclude="migrations,website/tosti/settings/*.py"
          --max-line-length=119
          website
