---

name: "Testing"
on:
  - push

jobs:
  build:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Install OS dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing libxmlsec1-dev pkg-config

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: "Test migrations"
        run: |
          uv run python website/manage.py makemigrations --no-input --check --dry-run

      - name: "Perform Django self-check"
        run: |
          uv run python3 website/manage.py check

      - name: "Run Django tests using Coverage"
        run: uv run coverage run website/manage.py test website/

      - name: "Check Coverage report"
        run: uv run coverage report --omit "*/site-packages/*,*/migrations/*"
